services:
  - type: web
    name: cozmo-ai-backend
    env: Node
    buildCommand: npm install
    startCommand: npm start
    rootDir: backend
    envVars:
      - key: DATABASE_URL
        fromDatabase: {
          name: cozmo-ai-db
        }
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 5000

  - type: static
    name: cozmo-ai-frontend
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://cozmo-ai-backend.onrender.com # This will be updated after backend deployment
